/**
 * Data Agent Provisioner
 *
 * Creates a Fabric Notebook in the target workspace containing the
 * `fabric-data-agent-sdk` provisioning script, then triggers it to run.
 * The notebook (when run inside Fabric's Spark environment) creates a
 * "Governly Data Agent" and attaches all supported data sources.
 *
 * The fabric-data-agent-sdk can only run inside Fabric notebooks – this
 * module handles all the REST API plumbing to get it there automatically.
 */

const https = require('https');

const FABRIC_API = 'https://api.fabric.microsoft.com/v1';

// ── Minimal HTTPS client ──────────────────────────────────────────────────────

function httpRequest(url, options = {}) {
  return new Promise((resolve, reject) => {
    const parsedUrl = new URL(url);
    const reqOptions = {
      hostname: parsedUrl.hostname,
      port:     parsedUrl.port || 443,
      path:     parsedUrl.pathname + (parsedUrl.search || ''),
      method:   options.method || 'GET',
      headers:  options.headers || {},
    };

    const req = https.request(reqOptions, (res) => {
      const chunks = [];
      res.on('data', (chunk) => chunks.push(chunk));
      res.on('end', () => {
        resolve({
          status:  res.statusCode,
          ok:      res.statusCode >= 200 && res.statusCode < 300,
          headers: res.headers,
          body:    Buffer.concat(chunks).toString(),
        });
      });
    });

    req.on('error', reject);
    if (options.body) req.write(options.body);
    req.end();
  });
}

// ── Notebook content ──────────────────────────────────────────────────────────

/**
 * Builds a Fabric Python notebook (.py format) that uses fabric-data-agent-sdk
 * to create a Data Agent and attach all workspace data sources.
 *
 * The workspace ID is resolved at runtime via notebookutils.fabric.getWorkspaceId()
 * so the same notebook works regardless of which workspace it is placed in.
 */
function buildNotebookPy(agentName) {
  return `# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {}
# META }

# CELL ********************

# Install the Fabric Data Agent SDK
%pip install fabric-data-agent-sdk

# MARKDOWN ********************

# ## Governly – Data Agent Provisioner
# Auto-generated by Governly. Run all cells to create a Fabric Data Agent
# and attach all supported data sources in this workspace.

# CELL ********************

import notebookutils as nu
import requests
from fabric.dataagent.client import create_data_agent, FabricDataAgentManagement

workspace_id = notebookutils.fabric.getWorkspaceId()
AGENT_NAME = "${agentName}"

print(f"Workspace ID : {workspace_id}")
print(f"Agent name   : {AGENT_NAME}")

# CELL ********************

try:
    agent = FabricDataAgentManagement(AGENT_NAME)
    print(f"Connected to existing Data Agent: {AGENT_NAME}")
except Exception:
    agent = create_data_agent(AGENT_NAME)
    print(f"Created new Data Agent: {AGENT_NAME}")

agent.update_configuration(
    instructions=(
        "You are a data analyst assistant for this Microsoft Fabric workspace. "
        "Help users understand, query, and analyze their data across all available "
        "data sources. Provide accurate, data-driven insights based on workspace data."
    )
)
print("AI instructions configured")

# CELL ********************

token = notebookutils.credentials.getToken("https://api.fabric.microsoft.com")
headers = {"Authorization": f"Bearer {token}"}

response = requests.get(
    f"https://api.fabric.microsoft.com/v1/workspaces/{workspace_id}/items",
    headers=headers,
)
response.raise_for_status()
workspace_items = response.json().get("value", [])
print(f"Found {len(workspace_items)} items in workspace")

# CELL ********************

DATASOURCE_TYPE_MAP = {
    "Lakehouse":     "lakehouse",
    "Warehouse":     "warehouse",
    "KQLDatabase":   "kqldatabase",
    "SemanticModel": "semanticmodel",
}

added = skipped = errors = 0
for item in workspace_items:
    ds_type = DATASOURCE_TYPE_MAP.get(item.get("type", ""))
    if not ds_type:
        skipped += 1
        continue
    try:
        agent.add_datasource(item["displayName"], type=ds_type)
        print(f"  + {item['type']}: {item['displayName']}")
        added += 1
    except Exception as e:
        print(f"  ! {item.get('displayName', '?')}: {e}")
        errors += 1

print(f"\\nResults: {added} added, {skipped} skipped, {errors} errors")

# CELL ********************

agent.publish()
print(f"\\n✅ Data Agent '{AGENT_NAME}' is published and ready!")
print("You can now use it in Fabric to query your data using natural language.")
`.replace('${agentName}', agentName);
}

// ── LRO helpers ───────────────────────────────────────────────────────────────

async function pollOperation(token, operationId, maxWaitMs = 120_000) {
  const start   = Date.now();
  const pollUrl = `${FABRIC_API}/operations/${operationId}`;

  while (Date.now() - start < maxWaitMs) {
    await new Promise(r => setTimeout(r, 3000));

    const resp = await httpRequest(pollUrl, {
      headers: { Authorization: `Bearer ${token}` },
    });

    if (!resp.ok) {
      throw new Error(`Operation poll failed (${resp.status}): ${resp.body.slice(0, 200)}`);
    }

    const data = JSON.parse(resp.body);
    console.log(`[DataAgent] Operation ${operationId}: ${data.status}`);

    if (data.status === 'Succeeded') return data;
    if (data.status === 'Failed') {
      throw new Error(`Operation failed: ${JSON.stringify(data.error ?? data).slice(0, 300)}`);
    }
  }

  throw new Error(`Operation timed out after ${maxWaitMs / 1000}s`);
}

async function getOperationResult(token, operationId) {
  const url  = `${FABRIC_API}/operations/${operationId}/result`;
  const resp = await httpRequest(url, {
    headers: { Authorization: `Bearer ${token}` },
  });

  if (!resp.ok) {
    throw new Error(`Get operation result failed (${resp.status}): ${resp.body.slice(0, 200)}`);
  }
  return JSON.parse(resp.body);
}

// ── Main provisioner ──────────────────────────────────────────────────────────

/**
 * Creates a Fabric Notebook with the Data Agent provisioning script and
 * triggers it to run.
 *
 * @param {string} token          - Fabric API Bearer token
 * @param {string} workspaceId    - Target workspace ID
 * @param {string} instanceName   - Governly instance display name (used to name the agent/notebook)
 * @returns {{ notebookId, notebookName, notebookUrl, jobTriggered, message }}
 */
async function provisionDataAgent(token, workspaceId, instanceName) {
  const agentName    = 'Governly Data Agent';
  const notebookName = `Governly - ${instanceName} - Data Agent Provisioner`;

  console.log(`[DataAgent] Provisioning for workspace ${workspaceId}, instance "${instanceName}"`);

  // Build notebook content (Fabric .py format)
  const notebookPy      = buildNotebookPy(agentName);
  const encodedNotebook = Buffer.from(notebookPy).toString('base64');

  const platformContent = JSON.stringify({
    $schema: 'https://developer.microsoft.com/json-schemas/fabric/gitIntegration/platformProperties/2.0.0/schema.json',
    metadata: { type: 'Notebook', displayName: notebookName },
    config:   { version: '2.0', logicalId: '00000000-0000-0000-0000-000000000000' },
  });
  const encodedPlatform = Buffer.from(platformContent).toString('base64');

  // ── Create the notebook item ───────────────────────────────────────────────
  const createBody = JSON.stringify({
    displayName: notebookName,
    type: 'Notebook',
    definition: {
      parts: [
        { path: 'notebook-content.py', payload: encodedNotebook, payloadType: 'InlineBase64' },
        { path: '.platform',           payload: encodedPlatform, payloadType: 'InlineBase64' },
      ],
    },
  });

  const authHeaders = {
    Authorization:  `Bearer ${token}`,
    'Content-Type': 'application/json',
    'Content-Length': String(Buffer.byteLength(createBody)),
  };

  console.log(`[DataAgent] Creating notebook "${notebookName}"...`);
  const createResp = await httpRequest(
    `${FABRIC_API}/workspaces/${workspaceId}/items`,
    { method: 'POST', headers: authHeaders, body: createBody }
  );

  let notebookId;

  if (createResp.status === 201) {
    notebookId = JSON.parse(createResp.body).id;
  } else if (createResp.status === 202) {
    const location = createResp.headers['location'] || createResp.headers['Location'] || '';
    const opMatch  = location.match(/\/operations\/([^/?]+)/i);
    if (!opMatch) throw new Error(`Unexpected Location header: ${location}`);

    const operationId = opMatch[1];
    console.log(`[DataAgent] Polling operation ${operationId}...`);
    await pollOperation(token, operationId);
    const result = await getOperationResult(token, operationId);
    notebookId = result.id;
  } else {
    throw new Error(`Failed to create notebook (${createResp.status}): ${createResp.body.slice(0, 400)}`);
  }

  console.log(`[DataAgent] Notebook created: ${notebookId}`);

  const notebookUrl = `https://app.fabric.microsoft.com/groups/${workspaceId}/notebooks/${notebookId}`;

  // ── Trigger notebook run ───────────────────────────────────────────────────
  let jobTriggered = false;
  try {
    const runBody    = JSON.stringify({ executionData: {} });
    const runHeaders = {
      Authorization:  `Bearer ${token}`,
      'Content-Type': 'application/json',
      'Content-Length': String(Buffer.byteLength(runBody)),
    };

    console.log(`[DataAgent] Triggering notebook run...`);
    const runResp = await httpRequest(
      `${FABRIC_API}/workspaces/${workspaceId}/items/${notebookId}/jobs/instances?jobType=RunNotebook`,
      { method: 'POST', headers: runHeaders, body: runBody }
    );

    if (runResp.status === 202 || runResp.ok) {
      jobTriggered = true;
      console.log(`[DataAgent] Notebook job triggered ✓`);
    } else {
      console.warn(`[DataAgent] Run trigger returned ${runResp.status}: ${runResp.body.slice(0, 200)}`);
    }
  } catch (runErr) {
    console.warn(`[DataAgent] Could not auto-trigger notebook: ${runErr.message}`);
  }

  return {
    notebookId,
    notebookName,
    notebookUrl,
    jobTriggered,
    message: jobTriggered
      ? `Notebook created and triggered. The Data Agent will be ready once the run completes.`
      : `Notebook created. Open it in Fabric and run all cells to create the Data Agent.`,
  };
}

module.exports = { provisionDataAgent };
