'use strict';

/**
 * Builds a Fabric-compatible .ipynb notebook JSON string for a DQ run.
 * @param {object} config
 *   runId       - string (HHMMSS generated at run time, used for cell IDs)
 *   workspaceId - string
 *   lakehouses  - Array<{ lakehouseId, lakehouseName, tables: [{tableName, columns}] }>
 *   dimensions  - string[]
 *
 * DQ_LAKEHOUSE_ID is resolved dynamically at notebook runtime via the Fabric REST API
 * (looks up "Governly_DQ" by display name). This means the notebook is portable across
 * deployments and survives lakehouse delete/recreate without re-pushing.
 */
function buildDqNotebook(config) {
  const { runId, workspaceId, lakehouses, dimensions, thresholds = {} } = config;

  const DEFAULT_THRESHOLDS = {
    completeness: 95.0,
    uniqueness:   95.0,
    validity:     98.0,
    consistency: 100.0,
    timeliness:  100.0,
  };
  const resolvedThresholds = { ...DEFAULT_THRESHOLDS, ...thresholds };

  // Serialise LAKEHOUSE_CONFIGS for Python
  const lhConfigPy = JSON.stringify(
    lakehouses.map(lh => ({
      lakehouse_id:   lh.lakehouseId,
      lakehouse_name: lh.lakehouseName,
      table_config:   Object.fromEntries(lh.tables.map(t => [t.tableName, t.columns])),
    })),
    null, 4
  );

  const dimensionsPy = JSON.stringify(dimensions);

  const lhSummary = lakehouses.map(lh => `${lh.lakehouseName} (${lh.lakehouseId})`).join(', ');

  function cell(type, source) {
    const base = { cell_type: type, id: Math.random().toString(36).slice(2, 10), metadata: {} };
    if (type === 'code') return { ...base, execution_count: null, outputs: [], source };
    return { ...base, source };
  }

  const headerLines = [
    `# Governly Data Quality Check\n`,
    `\n`,
    `**Source Lakehouses:** ${lhSummary}  \n`,
    `**DQ Results Lakehouse:** Governly_DQ (resolved dynamically at runtime)  \n`,
    `**Dimensions:** ${dimensions.join(', ')}  \n`,
    `\n`,
    `Run all cells in order. Results are written to the dedicated **Governly_DQ** lakehouse:\n`,
    `- Delta table \`governly_dq_results\` (partitioned by load_type/year/month/day/run_id)\n`,
    `- Delta table \`governly_dq_failed_rows\` (partitioned by load_type/year/month/day/run_id)\n`,
    `- JSON files in \`Files/governly_dq/year={year}/month={month}/day={day}/run_id={run_id}/\``
  ];

  const configLines = [
    `import json\n`,
    `import requests as _fab_req\n`,
    `from datetime import datetime\n`,
    `\n`,
    `WORKSPACE_ID = "${workspaceId}"\n`,
    `\n`,
    `# Resolve the Governly_DQ lakehouse ID dynamically — no hardcoded IDs\n`,
    `def _resolve_dq_lakehouse_id():\n`,
    `    token = mssparkutils.credentials.getToken("https://api.fabric.microsoft.com")\n`,
    `    r = _fab_req.get(\n`,
    `        f"https://api.fabric.microsoft.com/v1/workspaces/{WORKSPACE_ID}/lakehouses",\n`,
    `        headers={"Authorization": f"Bearer {token}"},\n`,
    `    )\n`,
    `    r.raise_for_status()\n`,
    `    for lh in r.json().get("value", []):\n`,
    `        if lh["displayName"] == "Governly_DQ":\n`,
    `            return lh["id"]\n`,
    `    raise RuntimeError("[DQ] Governly_DQ lakehouse not found. Create it from the Configure tab first.")\n`,
    `\n`,
    `DQ_LAKEHOUSE_ID = _resolve_dq_lakehouse_id()\n`,
    `print(f"[DQ] Resolved DQ lakehouse: Governly_DQ ({DQ_LAKEHOUSE_ID})")\n`,
    `\n`,
    `LOAD_TYPE      = "full"\n`,
    `FRESHNESS_DAYS = 7\n`,
    `\n`,
    `now    = datetime.utcnow()\n`,
    `year   = now.strftime("%Y")\n`,
    `month  = now.strftime("%m")\n`,
    `day    = now.strftime("%d")\n`,
    `run_id = now.strftime("%H%M%S")\n`,
    `RUN_TIMESTAMP = now.isoformat()\n`,
    `\n`,
    `# All lakehouses and tables to check — updated automatically by Governly\n`,
    `LAKEHOUSE_CONFIGS = ${lhConfigPy}\n`,
    `\n`,
    `DIMENSIONS = ${dimensionsPy}\n`,
    `\n`,
    `THRESHOLDS = {\n`,
    `    "completeness": ${resolvedThresholds.completeness.toFixed(1)},\n`,
    `    "uniqueness":   ${resolvedThresholds.uniqueness.toFixed(1)},\n`,
    `    "validity":     ${resolvedThresholds.validity.toFixed(1)},\n`,
    `    "consistency":  ${resolvedThresholds.consistency.toFixed(1)},\n`,
    `    "timeliness":   ${resolvedThresholds.timeliness.toFixed(1)},\n`,
    `}\n`,
    `\n`,
    `FAILURE_REASONS = {\n`,
    `    "completeness": "Value is null or empty",\n`,
    `    "uniqueness":   "Duplicate value detected",\n`,
    `    "validity":     "Invalid format or type mismatch",\n`,
    `    "consistency":  "Date/time range violated (start > end)",\n`,
    `    "timeliness":   "Data is stale beyond freshness threshold",\n`,
    `}\n`,
    `\n`,
    `def _read_path(lakehouse_id, sub):\n`,
    `    return f"abfss://{WORKSPACE_ID}@onelake.dfs.fabric.microsoft.com/{lakehouse_id}/{sub}"\n`,
    `\n`,
    `def _write_path(sub):\n`,
    `    return f"abfss://{WORKSPACE_ID}@onelake.dfs.fabric.microsoft.com/{DQ_LAKEHOUSE_ID}/{sub}"\n`,
    `\n`,
    `def _run_files_path():\n`,
    `    return _write_path(f"Files/governly_dq/year={year}/month={month}/day={day}/run_id={run_id}")\n`,
    `\n`,
    `lh_names = [c["lakehouse_name"] for c in LAKEHOUSE_CONFIGS]\n`,
    `print(f"[DQ] Run ID: {run_id}  Date: {year}-{month}-{day}")\n`,
    `print(f"[DQ] Checking {len(LAKEHOUSE_CONFIGS)} lakehouse(s): {', '.join(lh_names)}")\n`,
  ];

  const functionsLines = [
    `from pyspark.sql import functions as F\n`,
    `import hashlib\n`,
    `\n`,
    `def _safe_json(df):\n`,
    `    return F.to_json(F.struct(*[F.col(c).cast("string").alias(c) for c in df.columns]))\n`,
    `\n`,
    `def check_completeness(df, col, threshold):\n`,
    `    total = df.count()\n`,
    `    if total == 0: return 100.0, True, None, 0\n`,
    `    ok = df.filter(F.col(col).isNotNull() & (F.trim(F.col(col).cast("string")) != "")).count()\n`,
    `    metric = round((ok / total) * 100, 2)\n`,
    `    failed = df.filter(F.col(col).isNull() | (F.trim(F.col(col).cast("string")) == "")).select(\n`,
    `        _safe_json(df).alias("raw_values")).limit(1000) if metric < threshold else None\n`,
    `    return metric, metric >= threshold, failed, total\n`,
    `\n`,
    `def check_uniqueness(df, col, threshold):\n`,
    `    total = df.count()\n`,
    `    if total == 0: return 100.0, True, None, 0\n`,
    `    distinct = df.select(col).distinct().count()\n`,
    `    metric = round((distinct / total) * 100, 2)\n`,
    `    if metric < threshold:\n`,
    `        dup_rows = df.groupBy(col).count().filter(F.col("count") > 1).select(col).limit(200).collect()\n`,
    `        dup_vals = [r[0] for r in dup_rows if r[0] is not None]\n`,
    `        if dup_vals:\n`,
    `            failed = df.filter(F.col(col).isin(dup_vals)).select(\n`,
    `                _safe_json(df).alias("raw_values")).limit(1000)\n`,
    `        else:\n`,
    `            failed = df.filter(F.col(col).isNull()).select(_safe_json(df).alias("raw_values")).limit(1000)\n`,
    `    else:\n`,
    `        failed = None\n`,
    `    return metric, metric >= threshold, failed, total\n`,
    `\n`,
    `def check_validity(df, col, threshold):\n`,
    `    total = df.count()\n`,
    `    if total == 0: return 100.0, True, None, 0\n`,
    `    dtype = dict(df.dtypes).get(col, "string")\n`,
    `    if dtype in ("date", "timestamp", "datetime"):\n`,
    `        ok = df.filter(F.col(col).isNull() | F.col(col).cast("timestamp").isNotNull()).count()\n`,
    `    elif dtype in ("int", "long", "bigint", "short", "byte"):\n`,
    `        ok = df.filter(F.col(col).isNull() | F.col(col).cast("long").isNotNull()).count()\n`,
    `    elif dtype in ("double", "float", "decimal"):\n`,
    `        ok = df.filter(F.col(col).isNull() | F.col(col).cast("double").isNotNull()).count()\n`,
    `    else:\n`,
    `        ok = df.filter(F.col(col).isNull() | ~F.col(col).cast("string").rlike("[\\x00-\\x1f\\x7f]")).count()\n`,
    `    metric = round((ok / total) * 100, 2)\n`,
    `    failed = df.filter(F.col(col).isNotNull() & F.col(col).cast("string").rlike("[\\x00-\\x1f\\x7f]")).select(\n`,
    `        _safe_json(df).alias("raw_values")).limit(1000) if metric < threshold else None\n`,
    `    return metric, metric >= threshold, failed, total\n`,
    `\n`,
    `def check_consistency(df, col, threshold):\n`,
    `    PAIRS = [("start_date","end_date"),("start_time","end_time"),("created_at","updated_at"),\n`,
    `             ("valid_from","valid_to"),("begin_date","end_date"),("from_date","to_date")]\n`,
    `    cols_lower = {c.lower(): c for c in df.columns}\n`,
    `    cn = col.lower()\n`,
    `    pair = None\n`,
    `    for a, b in PAIRS:\n`,
    `        if cn == a and b in cols_lower: pair = (col, cols_lower[b])\n`,
    `        elif cn == b and a in cols_lower: pair = (cols_lower[a], col)\n`,
    `    if pair is None: return 100.0, True, None, 0\n`,
    `    ca, cb = pair\n`,
    `    total = df.count()\n`,
    `    if total == 0: return 100.0, True, None, 0\n`,
    `    ok = df.filter(F.col(ca).isNull() | F.col(cb).isNull() | (F.col(ca) <= F.col(cb))).count()\n`,
    `    metric = round((ok / total) * 100, 2)\n`,
    `    failed = df.filter(F.col(ca).isNotNull() & F.col(cb).isNotNull() & (F.col(ca) > F.col(cb))).select(\n`,
    `        _safe_json(df).alias("raw_values")).limit(1000) if metric < threshold else None\n`,
    `    return metric, metric >= threshold, failed, total\n`,
    `\n`,
    `def check_timeliness(df, col, freshness_days):\n`,
    `    dtype = dict(df.dtypes).get(col, "string")\n`,
    `    if "date" not in dtype and "time" not in dtype: return 100.0, True, None, 0\n`,
    `    total = df.count()\n`,
    `    if total == 0: return 100.0, True, None, 0\n`,
    `    max_val = df.agg(F.max(col)).collect()[0][0]\n`,
    `    if max_val is None: return 100.0, True, None, total\n`,
    `    from datetime import timedelta\n`,
    `    cutoff = datetime.utcnow() - timedelta(days=freshness_days)\n`,
    `    passed = max_val.timetuple() >= cutoff.timetuple() if hasattr(max_val, "timetuple") else False\n`,
    `    metric = 100.0 if passed else 0.0\n`,
    `    failed = df.filter(F.col(col) < F.lit(cutoff.isoformat()).cast("timestamp")).select(\n`,
    `        _safe_json(df).alias("raw_values")).limit(1000) if not passed else None\n`,
    `    return metric, passed, failed, total\n`,
    `\n`,
    `DIM_FUNCS = {\n`,
    `    "completeness": check_completeness,\n`,
    `    "uniqueness":   check_uniqueness,\n`,
    `    "validity":     check_validity,\n`,
    `    "consistency":  check_consistency,\n`,
    `    "timeliness":   check_timeliness,\n`,
    `}\n`
  ];

  const runChecksLines = [
    `all_results     = []\n`,
    `all_failed_rows = []\n`,
    `\n`,
    `for lh_cfg in LAKEHOUSE_CONFIGS:\n`,
    `    lh_id   = lh_cfg["lakehouse_id"]\n`,
    `    lh_name = lh_cfg["lakehouse_name"]\n`,
    `    print(f"\\n[DQ] === {lh_name} ({lh_id}) ===")\n`,
    `    for table_name, col_names in lh_cfg["table_config"].items():\n`,
    `        tbl_path = _read_path(lh_id, "Tables/" + table_name.replace(".", "/"))\n`,
    `        try:\n`,
    `            df = spark.read.format("delta").load(tbl_path)\n`,
    `            df.cache()\n`,
    `        except Exception as e:\n`,
    `            print(f"[DQ] Cannot load {table_name}: {e}")\n`,
    `            continue\n`,
    `        for col_name in col_names:\n`,
    `            if col_name not in df.columns:\n`,
    `                print(f"[DQ] Column {col_name} not in {table_name}")\n`,
    `                continue\n`,
    `            for dim in DIMENSIONS:\n`,
    `                fn = DIM_FUNCS.get(dim)\n`,
    `                if not fn: continue\n`,
    `                try:\n`,
    `                    args = (df, col_name, FRESHNESS_DAYS) if dim == "timeliness" else (df, col_name, THRESHOLDS[dim])\n`,
    `                    metric, passed, failed_df, total_rows = fn(*args)\n`,
    `                    rule_id = f"{table_name}__{col_name}__{dim}"\n`,
    `                    all_results.append({\n`,
    `                        "run_id": run_id, "load_type": LOAD_TYPE,\n`,
    `                        "year": year, "month": month, "day": day,\n`,
    `                        "table_name": table_name, "column_name": col_name,\n`,
    `                        "dimension": dim, "metric_name": f"{dim}_rate",\n`,
    `                        "metric_value": round(float(metric), 2),\n`,
    `                        "threshold": THRESHOLDS.get(dim, 100.0),\n`,
    `                        "passed": bool(passed), "total_rows": int(total_rows),\n`,
    `                        "run_timestamp": RUN_TIMESTAMP,\n`,
    `                        "source_lakehouse_id": lh_id,\n`,
    `                        "source_lakehouse_name": lh_name,\n`,
    `                    })\n`,
    `                    if failed_df is not None:\n`,
    `                        try:\n`,
    `                            for row in failed_df.collect():\n`,
    `                                all_failed_rows.append({\n`,
    `                                    "run_id": run_id, "load_type": LOAD_TYPE,\n`,
    `                                    "year": year, "month": month, "day": day,\n`,
    `                                    "table_name": table_name, "column_name": col_name,\n`,
    `                                    "dimension": dim, "rule_id": rule_id,\n`,
    `                                    "row_hash": hashlib.md5(row["raw_values"].encode()).hexdigest(),\n`,
    `                                    "raw_values": row["raw_values"],\n`,
    `                                    "failure_reason": FAILURE_REASONS.get(dim, "Rule check failed"),\n`,
    `                                    "run_timestamp": RUN_TIMESTAMP,\n`,
    `                                })\n`,
    `                        except Exception as row_err:\n`,
    `                            print(f"[DQ] Warning: row capture failed for {table_name}.{col_name} [{dim}]: {row_err}")\n`,
    `                    status = "PASS" if passed else "FAIL"\n`,
    `                    print(f"[DQ] {table_name}.{col_name} [{dim}]: {metric:.1f}% ({status}, {total_rows} rows)")\n`,
    `                except Exception as e:\n`,
    `                    print(f"[DQ] Error {table_name}.{col_name} [{dim}]: {e}")\n`,
    `        df.unpersist()\n`,
    `\n`,
    `print(f"\\n[DQ] Total: {len(all_results)} result rows, {len(all_failed_rows)} failed rows")\n`
  ];

  const writeDeltaLines = [
    `def _safe_write_delta(df, table_path, partition_cols):\n`,
    `    try:\n`,
    `        df.write.format("delta").mode("append") \\\n`,
    `            .option("mergeSchema", "true") \\\n`,
    `            .partitionBy(*partition_cols) \\\n`,
    `            .save(table_path)\n`,
    `    except Exception as e:\n`,
    `        print(f"[DQ] Write failed ({type(e).__name__}: {str(e)[:200]}) — dropping and recreating {table_path}")\n`,
    `        try:\n`,
    `            dbutils.fs.rm(table_path, recurse=True)\n`,
    `        except Exception:\n`,
    `            pass\n`,
    `        df.write.format("delta").mode("overwrite") \\\n`,
    `            .option("overwriteSchema", "true") \\\n`,
    `            .partitionBy(*partition_cols) \\\n`,
    `            .save(table_path)\n`,
    `\n`,
    `if all_results:\n`,
    `    _safe_write_delta(\n`,
    `        spark.createDataFrame(all_results),\n`,
    `        _write_path("Tables/governly_dq_results"),\n`,
    `        ["load_type", "year", "month", "day", "run_id"]\n`,
    `    )\n`,
    `    print(f"[DQ] Written {len(all_results)} rows to Governly_DQ/governly_dq_results")\n`,
    `\n`,
    `if all_failed_rows:\n`,
    `    _safe_write_delta(\n`,
    `        spark.createDataFrame(all_failed_rows),\n`,
    `        _write_path("Tables/governly_dq_failed_rows"),\n`,
    `        ["load_type", "year", "month", "day", "run_id"]\n`,
    `    )\n`,
    `    print(f"[DQ] Written {len(all_failed_rows)} rows to Governly_DQ/governly_dq_failed_rows")\n`
  ];

  const exportJsonLines = [
    `run_path = _run_files_path()\n`,
    `lh_ids   = [c["lakehouse_id"]   for c in LAKEHOUSE_CONFIGS]\n`,
    `lh_names = [c["lakehouse_name"] for c in LAKEHOUSE_CONFIGS]\n`,
    `\n`,
    `summary = {\n`,
    `    "run_id":               run_id,\n`,
    `    "run_timestamp":        RUN_TIMESTAMP,\n`,
    `    "source_lakehouse_id":  lh_ids[0]   if len(lh_ids)   == 1 else lh_ids,\n`,
    `    "source_lakehouse_name": lh_names[0] if len(lh_names) == 1 else ", ".join(lh_names),\n`,
    `    "lakehouse_id":         lh_ids[0]   if len(lh_ids)   == 1 else lh_ids,\n`,
    `    "year": year, "month": month, "day": day,\n`,
    `    "results": all_results,\n`,
    `}\n`,
    `mssparkutils.fs.put(f"{run_path}/summary.json", json.dumps(summary, indent=2), True)\n`,
    `\n`,
    `failed_export = {"run_id": run_id, "failed_rows": all_failed_rows}\n`,
    `mssparkutils.fs.put(f"{run_path}/failed_rows.json", json.dumps(failed_export, indent=2), True)\n`,
    `\n`,
    `print(f"[DQ] Exported JSON to {run_path}/")\n`,
    `print("[DQ] Data quality run complete!")\n`
  ];

  const notebook = {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: { display_name: 'Synapse PySpark', language: 'Python', name: 'synapse_pyspark' },
      language_info: { name: 'python' },
    },
    cells: [
      cell('markdown', headerLines),
      cell('code',     configLines),
      cell('code',     functionsLines),
      cell('code',     runChecksLines),
      cell('code',     writeDeltaLines),
      cell('code',     exportJsonLines),
    ],
  };

  return JSON.stringify(notebook);
}

module.exports = { buildDqNotebook };
